### ISSUE TITLE
In which hidden layer is there a skip connection?

### ISSUE THREAD

**Issue by Touka20** [yenchenlin/nerf-pytorch#115]
The paper and the official code both concatenate the input to the fifth layer’s activation. But maybe this PyTorch version actually concatenate it to the sixth layer?

this version, where `skip=[4]`
````
self.pts_linears = nn.ModuleList(
            [nn.Linear(input_ch, W)] + [nn.Linear(W, W) if i not in self.skips else nn.Linear(W + input_ch, W) for i in range(D-1)])
````

official code, where `skip=[4]`
```
for i in range(D):
    outputs = dense(W)(outputs)
    if i in skips:
        outputs = tf.concat([inputs_pts, outputs], -1)
```

![image](https://user-images.githubusercontent.com/125424658/232308753-4fd79a74-e8ef-45d9-80d3-278b3bd641f1.png)

**Comment by Touka20** [comment]
The paper and the official code both concatenate the
input to the fifth layer’s activation. But maybe the PyTorch version actually concatenate it to the sixth layer?

**Comment by Demonss3** [comment]
The i here is counted from 0, so when i=4, it refers to the fifth layer of activation layer, which is consistent with the version of the paper and tensorflow

**Comment by Touka20** [comment]
> The i here is counted from 0, so when i=4, it refers to the fifth layer of activation layer, which is consistent with the version of the paper and tensorflow

Thank you, I got it.

**Comment by Touka20** [comment]
> The i here is counted from 0, so when i=4, it refers to the fifth layer of activation layer, which is consistent with the version of the paper and tensorflow

Thank you I got it!
Actually I know that i is counted from 0, but I mistook some basic concepts.
The input is concatenated to the 5th layer's output instead of input, so it's a part of the 6th layer's input.
I think maybe it's time for me to reveal some basic but important concepts for deep learning haha.
