### ISSUE TITLE
nerf的网络层最后是不是少一个sigmoid激活函数？

### ISSUE THREAD

**Issue by graceforlife** [yenchenlin/nerf-pytorch#145]
您好，我看论文里面，在最后的全连接128->RGB 3的时候，论文说明这里有一个sigmoid activation。可是我看您代码中似乎并没有加上activation，而是直接全连接了，请问这是为什么？
![屏幕截图 2024-11-05 102213](https://github.com/user-attachments/assets/17112909-7e67-4d4c-b49b-cc51fdb6f9c2)

**Comment by Zhengyu-Hu** [comment]
在https://github.com/yenchenlin/nerf-pytorch/blob/63a5a630c9abd62b0f21c08703d0ac2ea7d4b9dd/run_nerf.py#L282
没有在NeRF类里面做，alpha的ReLu也是一样的，在这个函数里面处理的

**Comment by yenchenlin** [comment]
@Zhengyu-Hu thank you for answering the question.
