### ISSUE TITLE
Can't run a pre-trained model 

### ISSUE THREAD

**Issue by yosipk** [yenchenlin/nerf-pytorch#15]
Hi! Thanks for the PyTorch implementation, looks great! 

I tried to run pre-trained model:
```
python3 run_nerf.py --config configs/lego.txt --render_only
```
but it seems `load_blender.py` assumes there should be another file `data/nerf_synthetic/lego/transforms_train.json`, but it's not in the repo nor it comes with pre-trained models:
```
Traceback (most recent call last):
  File "run_nerf.py", line 860, in <module>
    train()
  File "run_nerf.py", line 570, in train
    images, poses, render_poses, hwf, i_split = load_blender_data(args.datadir, args.half_res, args.testskip)
  File "[PATH]/nerf-pytorch/load_blender.py", line 41, in load_blender_data
    with open(os.path.join(basedir, 'transforms_{}.json'.format(s)), 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: './data/nerf_synthetic/lego/transforms_train.json'
```

Am I missing something?

Thanks!

**Comment by yenchenlin** [comment]
Hello @yosipk , I believe it comes with the dataset [here](https://drive.google.com/drive/folders/1lrDkQanWtTznf48FCaW5lX9ToRdNDF1a).

**Comment by 07hyx06** [comment]
Hi! I put the pre-train weight in .logs/lego_test/200000.tar, but it seems the program cannot find it. 
Am I missing something?
![image](https://user-images.githubusercontent.com/52267384/106538686-973e9600-6537-11eb-958d-19f85712c2ac.png)

**Comment by yenchenlin** [comment]
@07hyx06 

1. Change [this line](https://github.com/yenchenlin/nerf-pytorch/blob/master/configs/lego.txt#L1) to `lego_test`.
2. Comment out [this line[(https://github.com/yenchenlin/nerf-pytorch/blob/master/run_nerf.py#L192) as pre-trained models are trained with a single GPU.

**Comment by 07hyx06** [comment]
> @07hyx06
> 
> 1. Change [this line](https://github.com/yenchenlin/nerf-pytorch/blob/master/configs/lego.txt#L1) to `lego_test`.
> 2. Comment out [this line](https://github.com/yenchenlin/nerf-pytorch/blob/master/run_nerf.py#L192) as pre-trained models are trained with a single GPU.

It works well! Thx for your quick reply!

**Comment by 07hyx06** [comment]
A question about i-NeRF. What about the results of i-NeRF in Table 2 without superpoint+superglue initialization? Does i-NeRF work well when there exists is a large gap between the initial pose and the ground truth pose?

The i-NeRF repo is not released so I commented here.......

**Comment by harelwa** [comment]
> 1. lego_test

@yenchenlin  pls note that Instead of modifying `configs/lego.txt`, you can provide `--expname` - 

```bash
python run_nerf.py --config configs/lego.txt --render_only --expname lego_test
```

> this will override the value loaded from the config file
