### ISSUE TITLE
Help obtaining .json files from blender objects

### ISSUE THREAD

**Issue by yggs1401** [yenchenlin/nerf-pytorch#16]
Hello! How can you make new poses and create .json files from new synthetic objects. I have an object I made in Blender and I want to obtain those to complete the dataset. 
Thank you and stay safe!

**Comment by yenchenlin** [comment]
Yes, you can. Here is an example script for rendering ShapeNet objects.
 
https://github.com/vsitzmann/shapenet_renderer
