### ISSUE TITLE
assert triggered!

### ISSUE THREAD

**Issue by HsiangYangChu** [yenchenlin/nerf-pytorch#19]
python run_nerf.py --config configs/fern.txt --render_only
Loaded image data (378, 504, 3, 20) [378.         504.         407.56579161]
Loaded ./data/nerf_llff_data/fern 16.985296178676084 80.00209740336334
recentered (3, 5)
[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00  1.4901161e-09]
 [ 0.0000000e+00  1.0000000e+00 -1.8730975e-09 -9.6857544e-09]
 [-0.0000000e+00  1.8730975e-09  1.0000000e+00  0.0000000e+00]]
Data:
(20, 3, 5) (20, 378, 504, 3) (20, 2)
HOLDOUT view is 12
Loaded llff (20, 378, 504, 3) (120, 3, 5) [378.     504.     407.5658] ./data/nerf_llff_data/fern
Auto LLFF holdout, 8
DEFINING BOUNDS
NEAR FAR 0.0 1.0
Found ckpts ['./logs/fern_test/200000.tar']
Reloading from ./logs/fern_test/200000.tar
RENDER ONLY
test poses shape torch.Size([120, 3, 5])
  0%|                                                                                                                                                                                                 | 0/120 [00:00<?, ?it/s]0 0.003157377243041992
  0%|                                                                                                                                                                                                 | 0/120 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "run_nerf.py", line 858, in <module>
    train()
  File "run_nerf.py", line 650, in train
    rgbs, _ = render_path(render_poses, hwf, args.chunk, render_kwargs_test, gt_imgs=images, savedir=testsavedir, render_factor=args.render_factor)
  File "run_nerf.py", line 154, in render_path
    rgb, disp, acc, _ = render(H, W, focal, chunk=chunk, c2w=c2w[:3,:4], **render_kwargs)
  File "run_nerf.py", line 126, in render
    all_ret = batchify_rays(rays, chunk, **kwargs)
  File "run_nerf.py", line 59, in batchify_rays
    ret = render_rays(rays_flat[i:i+chunk], **kwargs)
  File "run_nerf.py", line 393, in render_rays
    z_samples = sample_pdf(z_vals_mid, weights[...,1:-1], N_importance, det=(perturb==0.), pytest=pytest)
  File "/home/zhuxiangyang/work/nerf-pytorch/run_nerf_helpers.py", line 227, in sample_pdf
    below = torch.max(torch.zeros_like(inds-1), inds-1)
RuntimeError: CUDA error: invalid device function
Segmentation fault (core dumped)

**Comment by yenchenlin** [comment]
What's the output of `nvcc --version`? I am using CUDA 10.1

**Comment by yenchenlin** [comment]
Closing due to no updated response ... feel free to bump it back if anything is wrong.

**Comment by nicschoen** [comment]
Just in case someone else is having the same issue. I installed pytorch via `conda install pytorch==1.4.0 torchvision==0.5.0 cudatoolkit=10.1 -c pytorch` but have CUDA 10.0 installed. Reinstalling pytorch with `cudatoolkit=10.0` and reinstalling torchsearchsorted afterwards solved the problem.

**Comment by yenchenlin** [comment]
Thank you!
