### ISSUE TITLE
can you provide a demo of extracting mesh?

### ISSUE THREAD

**Issue by universewill** [yenchenlin/nerf-pytorch#2]
can you provide a demo of extracting mesh?

**Comment by yenchenlin** [comment]
I think the example from original repo [here](https://github.com/bmild/nerf/blob/master/extract_mesh.ipynb) would work. 

The only additional step is to transform a pytorch pre-trained weights into `.npy` format. Is that what you are asking for?

**Comment by yenchenlin** [comment]
You can look at [this function](https://github.com/yenchenlin/nerf-pytorch/blob/master/run_nerf_helpers.py#L124-L151) on how to transform a trained torch model's weights into `.npy` format. 

Will close the issue for now but feel free to re-open it once you run into any issue.

**Comment by zachfang** [comment]
@universewill I recently submitted a commit to add `extract_mesh.ipynb` into this repo and it's been merged in case you still need that.
