### ISSUE TITLE
output_ch = 5 if args.N_importance > 0 else 4

### ISSUE THREAD

**Issue by Xiangjun-Gao** [yenchenlin/nerf-pytorch#22]
Thanks for your work!
Why it is 5 in this code?
`output_ch = 5 if args.N_importance > 0 else 4`

**Comment by yenchenlin** [comment]
It should be 4, that line is there due to historical reasons :)

Do you want to submit a PR for it?

**Comment by Xiangjun-Gao** [comment]
Yeah, I'd love to.

**Comment by yenchenlin** [comment]
Thanks, closing this issue now.
