### ISSUE TITLE
5D input or 6D input ?

### ISSUE THREAD

**Issue by Xiangjun-Gao** [yenchenlin/nerf-pytorch#25]
In nerf paper, they use a 5D input (x; y; z; θ; φ). In this implementation, the input is 6D, which is inconsistent with nerf paper.

**Comment by yenchenlin** [comment]
Hello @Xiangjun-Gao , you can see that the official implementation also used 6D input: https://github.com/bmild/nerf/blob/master/run_nerf_helpers.py#L80

**Comment by Xiangjun-Gao** [comment]
Thanks for your reply~

**Comment by LYY-HH** [comment]
So the description in the paper is not absolutely correct ?
