### ISSUE TITLE
parameters of searchsorted

### ISSUE THREAD

**Issue by btwbtm** [yenchenlin/nerf-pytorch#26]
https://github.com/yenchenlin/nerf-pytorch/blob/333f2be3baabe30701f894ac19b8a8ce3c9f3cb5/run_nerf_helpers.py#L232

It seems that the last parameter of searchsorted is side='left' ? Why do you use right=True here?

**Comment by yenchenlin** [comment]
Following the original implementation [here](https://github.com/bmild/nerf/blob/55d8b00244d7b5178f4d003526ab6667683c9da9/run_nerf_helpers.py#L199).
