### ISSUE TITLE
Issue with training low-res lego NeRF

### ISSUE THREAD

**Issue by Bingrong89** [yenchenlin/nerf-pytorch#28]
Hi, I followed the instructions to train the low-res lego NeRF.
But at iteration 100,000 I realized the disp_map video saved was an invalid file.
Upon investigating, the disp_map array being saved contained np.nan values.(Also, I switched the video writing from using imageio library to cv2 library.)

This was traced to line 387 in run_nerf.py.
    _raw = network_query_fn(pts, viewdirs, network_fn)_
Some rows of raw[...,3] , representing density, were negative.

Then at line 277, under the function raw2outputs(line 264):
_raw2alpha = lambda raw, dists, act_fn=F.relu: 1.-torch.exp(-act_fn(raw)*dists)_ 
evaluates to zero, due to ReLU on negative value.
This leads to the np.nan values appearing in disp_map within the same function block.

So I would like to ask,
Am I doing something wrong here? Or is this an expected behaviour? Please kindly advise

**Comment by yenchenlin** [comment]
Does it happen before iteration 100,000?

**Comment by Bingrong89** [comment]
Yes, it does happen before iteration 100,000. The video saved at iteration 50,000 suffers from the same problem.

**Comment by Bingrong89** [comment]
Division by zero is obviously not an expected behaviour, shouldnt have asked..sorry.
