### ISSUE TITLE
Deeper Network for views

### ISSUE THREAD

**Issue by BrianPugh** [yenchenlin/nerf-pytorch#3]
Have you experimented with your commented out code here? Did it help/harm performance?

https://github.com/yenchenlin/nerf-pytorch/blob/master/run_nerf_helpers.py#L90

Seems like the paper and the official TF implementation do different things.

**Comment by yenchenlin** [comment]
Authors have replied to the architecture issue [here](https://github.com/bmild/nerf/issues/11)

I didn't try to make the model deeper as current architecture fit into my GPU's memory perfectly. It would be interesting to benchmark indeed.

**Comment by krrish94** [comment]
As an aside, I tried a shallower arch, and got similar performance.
https://github.com/krrish94/nerf-pytorch

**Comment by yenchenlin** [comment]
@krrish94 just curious, how small the model could be and how you ensure it gets similar performance? I am exploring an idea where smaller model could be really useful, thanks!

**Comment by krrish94** [comment]
I used 4 layers for the coordinates (xyz) with a hidden size of 64, and one layer for the rgb prediction (size 32). For reference, I used the `FlexibleNeRFModel` here https://github.com/krrish94/nerf-pytorch/blob/master/nerf/models.py#L185
with the following instantiation
```
FlexibleNeRFModel(num_layers=4, hidden_size=64, num_encoding_fn_xyz=10, num_encoding_fn_dir=4, include_input_xyz=True, include_input_dir=True)
```

**Comment by yenchenlin** [comment]
cool, thanks!
