### ISSUE TITLE
extract mesh

### ISSUE THREAD

**Issue by tiexuedanxin** [yenchenlin/nerf-pytorch#31]
Hello, Could you provide a demo code to extract mesh?

**Comment by yenchenlin** [comment]
Here: https://github.com/yenchenlin/nerf-pytorch/blob/master/extract_mesh.ipynb

**Comment by tiexuedanxin** [comment]
> Here: https://github.com/yenchenlin/nerf-pytorch/blob/master/extract_mesh.ipynb

hello, Is the code can extract high quality color mesh, or is there some way to extract high quality color mesh. thank you.
