### ISSUE TITLE
Abnormal Render Result.

### ISSUE THREAD

**Issue by KerryKou** [yenchenlin/nerf-pytorch#33]
Hi, thank you for your excellent work! There is a problem.  When I run `python run_nerf.py --config configs\fern.txt --render_only`, the render result I got was weird. All intermediate images I got from ./fern_test/renderonly_path_200000 look like this:
![000](https://user-images.githubusercontent.com/44169742/114517003-7d74aa00-9c70-11eb-8f01-2b576fcf097c.png)
I have no idea about why this happens and how to fix it.

**Comment by salykovaa** [comment]
@KerryKou Hey, I have the same problem. May be the error is occurred because of the new version 1.8.1 of pytorch? Can you please try to run the script with pytorch 1.7.0 or 1.4.0?

**Comment by salykovaa** [comment]
@KerryKou did you change any parameters in the config file \configs\lego.txt?

**Comment by KerryKou** [comment]
> @KerryKou Hey, may be the error occurred because of the new version 1.8.1 of pytorch? Can you please try to run the script with pytorch 1.7.0 or 1.4.0?

@salykovaa Thank you for your advices! I have tried to use pytorch 1.7.0 and 1.4.0, but the result kept same. This is part of my environment dependencies:

- torch==1.7.0
- torchvision==0.8.0
- imageio==2.9.0
- imageio-ffmpeg ==0.4.3
- matplotlib==3.3.3
- opencv-python==4.5.1.48

It seems that there is no conflict with the requirements.txt. And I also checked my config files. I am sure that they haven't been modified.

**Comment by salykovaa** [comment]
@KerryKou try to change [this line](https://github.com/yenchenlin/nerf-pytorch/blob/9aeae005f468ff18b090396d903a22411f8a4509/configs/lego.txt#L1) to `expname=lego_test`. Hopefully it works

**Comment by salykovaa** [comment]
@KerryKou Just to be sure: did you put your "fern_test" folder in the "logs" folder? After running the script you should see something like this in the console: 
```
Found ckpts ['./logs/fern_test/200000.tar']
Reloading from ./logs/fern_test/200000.tar
```

**Comment by KerryKou** [comment]
> @KerryKou Just to be sure: did you put your "fern_test" folder into the "logs" folder? After running the script you should see something like this in the console:
> 
> ```
> Found ckpts ['./logs/fern_test/200000.tar']
> Reloading from ./logs/fern_test/200000.tar
> ```

@salykovaa Yes, I am sure I put it correctly. This what I got from console:
![image](https://user-images.githubusercontent.com/44169742/114998637-be202d80-9ed3-11eb-8f82-a2d8df4984e0.png)

**Comment by salykovaa** [comment]
@KerryKou I downloaded the whole repository from this [checkpoint](https://github.com/yenchenlin/nerf-pytorch/tree/f38216f43d1939976b440b71290c18ffaab278fa) and I used the following dependencies:
```
torch==1.4.0
torchvision==0.5.0
imageio
imageio-ffmpeg
matplotlib
configargparse
tensorboard==1.14.0
tqdm
opencv-python==4.2.0.34
```
The script works perfectly and the output images are correct. If you use these dependencies, don't forget to install torchsearched manually via `cd torchsearchsorted pip install .`

If it doesn't help you, I assume the error occurs, because you use 2 GPUs (but I am not sure, just an assumption)

**Comment by KerryKou** [comment]
> @KerryKou I downloaded the whole repository from this [checkpoint](https://github.com/yenchenlin/nerf-pytorch/tree/f38216f43d1939976b440b71290c18ffaab278fa) and I used the following dependencies:
> 
> ```
> torch==1.4.0
> torchvision==0.5.0
> imageio
> imageio-ffmpeg
> matplotlib
> configargparse
> tensorboard==1.14.0
> tqdm
> opencv-python==4.2.0.34
> ```
> 
> The script works perfectly and the output images are correct. If you use these dependencies, don't forget to install torchsearched manually via `cd torchsearchsorted pip install .`
> 
> If it doesn't help you, I assume the error occurs, because you use 2 GPUs (but I am not sure, just an assumption)

@salykovaa I tried to clone from the repository you provided. As you say, it works perfectly. I will go on to find out what causes the abnormal results. Thank you for your help!

**Comment by salykovaa** [comment]
@KerryKou You are welcome! My assumption: since the model was trained with torch 1.4.0, we also need to test it with 1.4.0, but maybe I understood this wrong. Anyway, it would be nice if you could find what causes the abnormal result.

**Comment by yenchenlin** [comment]
Hi all, thanks for raising up the issues. I've temporarily rolled back the master branch to [this checkpoint](https://github.com/yenchenlin/nerf-pytorch/tree/f38216f43d1939976b440b71290c18ffaab278fa), and move all the updates to branch `dev`.

The error could come from other people's pull requests, I will try to debug on my side when I have time too.
