### ISSUE TITLE
What is 'camera_angle_x' and 'rotation' in data ?

### ISSUE THREAD

**Issue by MayuOshima** [yenchenlin/nerf-pytorch#41]
Hello, thanks for your excellent implementation.

I am sorry but because I am new to this area. When I open the data file, say transforms_test.json, I find that there are keys named 'camera_angle_x' and 'rotation'.
Could you please explain the two keys in detail?  If I guess right, they are parameters about the camera pose. But why 'transform_matrix' is not enough to represent the camera pose? Why do we need 'camera_angle_x' and 'rotation' and how to get them?
Thanks!

**Comment by yenchenlin** [comment]
Hello,

`camera_angle_x` is the horizontal field of view.

The following relationship holds for the camera:

```
focal = 0.5 * image_width / np.tan(0.5 * camera_angle_x)
```

**Comment by DouYishun** [comment]
Hi @yenchenlin, thanks for your excellent implementation. 
What about the "rotation"? (I didn't find it in code.)
Thanks.

**Comment by elenacliu** [comment]
Yes, I think the rotation doesn't have any function in the code. @Yishun99
