### ISSUE TITLE
torch.autograd.set_detect_anomaly(True) seems slow down the training 

### ISSUE THREAD

**Issue by formyfamily** [yenchenlin/nerf-pytorch#42]
Hi,

Thanks for the work on this repo! I just found that calling this function (line 2 of run_nerf_helpers.py) can somehow slow down the training process by a large amount (almost 50% in my computer). Since this is a debugging option I'd like to suggest to turn it off as default. How do you think?

Thanks!

**Comment by yenchenlin** [comment]
Sounds good, done. Huge thanks for the suggestion!
