### ISSUE TITLE
Seems not converge on Lego

### ISSUE THREAD

**Issue by xrenaa** [yenchenlin/nerf-pytorch#5]
Hi,  thanks for your great PyTorch implementation! 
After running on the lego data, I found the loss is around 0.13 and the output video and test frames are all white or black.

![010](https://user-images.githubusercontent.com/31800248/79159204-f203d700-7dd7-11ea-97f8-7251021e4d0c.png)

Hope for your help! Thank you!

**Comment by yenchenlin** [comment]
Hello, may I know your config?

**Comment by xrenaa** [comment]
Hi, thanks for your reply! I just follow the setting in the repo:

```
expname = lego_test
basedir = ./logs
datadir = ./data/nerf_synthetic/lego
dataset_type = blender

half_res = True

N_samples = 64
N_importance = 64

use_viewdirs = True

white_bkgd = True

N_rand = 1024
```

And I follow the installation of the environment.

<img width="476" alt="截屏2020-04-14上午1 19 09" src="https://user-images.githubusercontent.com/31800248/79169880-f2a76800-7ded-11ea-8801-51a51c8f2619.png">

However, the loss seems not to change and gets stuck about 0.13. This is weird. I do not change any of the original repo. Thank you!

**Comment by yenchenlin** [comment]
Hello, interestingly my machine's outputs are normal. Check my output for the first 250 steps [here](https://github.com/yenchenlin/nerf-pytorch/files/4472407/tmp.txt). It should drop down to ~0.03 after 250 steps.

I am attaching my setting for the experiments here:

- [config.txt](https://github.com/yenchenlin/nerf-pytorch/files/4472410/config.txt)
- [args.txt](https://github.com/yenchenlin/nerf-pytorch/files/4472408/args.txt)
-

**Comment by yenchenlin** [comment]
@xrenaa any update on this?

**Comment by xrenaa** [comment]
@yenchenlin  Hi, I tried to re-clone the file and create new conda environments multiple times of both python 3.6 and 3.7 versions. However, the loss still stuck about 0.13. I am still trying to figure out the reason. And my output is the same as yours.

**Comment by yenchenlin** [comment]
I see, I will do my best to help. Can you report the PyTorch version you are running?

**Comment by xrenaa** [comment]
Hi, I run on PyTorch 1.4 and Cuda 10.1.
<img width="505" alt="截屏2020-04-16上午1 47 10" src="https://user-images.githubusercontent.com/31800248/79399639-3207bd00-7f84-11ea-9403-aa0535e39a66.png">

And I find an interesting thing. At first, the RGB video is plain white and after about 600k iters, the loss come to 0.01 and the video becomes to like this:

<img width="394" alt="截屏2020-04-16上午1 48 49" src="https://user-images.githubusercontent.com/31800248/79399728-6bd8c380-7f84-11ea-9bd0-a16e800259d2.png">

**Comment by yenchenlin** [comment]
Hello @xrenaa , I think the package's version looks right. Do you have other machines to test this? Today, I test it on two brand new machines and it works normally. Let me know if you can reproduce the same issue on multiple machines.

I am using mini-conda to create the environment:
```
conda create -n tmp python=3.6
conda activate tmp
```

**Comment by yenchenlin** [comment]
Hello @xrenaa , I've added the cropping operation suggested by the authors [here](https://github.com/yenchenlin/nerf-pytorch/commit/16be72ba5b4a816053a5642dca6cd428bc3048d4). It helped me solve the "all white" issue on `drums` and `mic`. 

Do you want to try it again? You just need to re-clone the code and run the same instructions.

**Comment by xrenaa** [comment]
Hi @yenchenlin , I am happy to see it converge finally. Thanks for your update! 

<img width="460" alt="截屏2020-04-17下午12 31 00" src="https://user-images.githubusercontent.com/31800248/79560151-4db7b400-80a7-11ea-99cc-d9d101917b37.png">

I will close this issue.

**Comment by yenchenlin** [comment]
Glad to know it work! In my experiences, adding this whenever `white_bkgd = True` helps a lot :)

**Comment by kwea123** [comment]
I also have this problem with my implementation. The problem is indeed due to all white sampling, which is totally by chance... so I just rerun the experiment if I see the loss doesn't go down after ~100 steps, and finally it will work when I'm lucky in the first iters..

**Comment by yenchenlin** [comment]
@kwea123 tried the cropping solution I mentioned, it eliminates the need for luck.

**Comment by kwea123** [comment]
Increasing the batch size or changing the optimizer (I use RAdam) also solves the problem for me.

**Comment by hengfei-wang** [comment]
I have the same problem on my own llff data. Actually, loss went down quickly and converged in a short time in my experiment. But the final rendering images are all black. I see that all your experiments didn't converge at the first stage which is different with my problem. Any idea?

**Comment by Chan0081** [comment]
I tried both the configs:

1. current ./configs/lego.txt:

```
expname = blender_paper_lego
basedir = ./logs
datadir = ./data/nerf_synthetic/lego
dataset_type = blender

no_batching = True

use_viewdirs = True
white_bkgd = True
lrate_decay = 500

N_samples = 64
N_importance = 128
N_rand = 1024

precrop_iters = 500
precrop_frac = 0.5

half_res = True
```

2. previous config:

```
expname = lego_test
basedir = ./logs
datadir = ./data/nerf_synthetic/lego
dataset_type = blender

half_res = True

N_samples = 64
N_importance = 64

use_viewdirs = True

white_bkgd = True

N_rand = 1024
```

and the first output is all white, while the second produces a reasonable result ...

**Comment by IntentionsY** [comment]
Hello，I need help.Please!!!
I inputed"python run_nerf.py --config configs/lego.txt",then 
![q1](https://github.com/yenchenlin/nerf-pytorch/assets/112459194/5d66a74b-5d3a-43c5-86b9-ebd6c11fc743)
it shows"no ndc"
![q2](https://github.com/yenchenlin/nerf-pytorch/assets/112459194/0d922ab1-fb1f-4be3-b10b-9d8826d7b6fb)
please help me ,thank you.

你好，我在pycharm中导入项目之后，加载数据lego.txt在data/nerf_synthetic目录下，开始训练数据，输入python run_nerf.py --config configs/lego.txt，却显示没有ndc，而且val不进行，为0。显示结果如下
![Uploading q3.png…]()
请帮帮我，谢谢你

**Comment by IntentionsY** [comment]
![q4](https://github.com/yenchenlin/nerf-pytorch/assets/112459194/bab62124-2847-40d5-b630-1b3c0ba0264d)
![q5](https://github.com/yenchenlin/nerf-pytorch/assets/112459194/76d184bc-11a2-4e4f-ba7b-9c1c90ea8e24)
the question is above
